<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="10062" started-at="2018-01-11T13:15:38Z" finished-at="2018-01-11T13:15:48Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="10062" started-at="2018-01-11T13:15:38Z" finished-at="2018-01-11T13:15:48Z">
      <class name="scenarios.AppiumTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:scenarios.AppiumTest@6d00a15d]" name="setUp" is-config="true" duration-ms="8" started-at="2018-01-11T14:15:38Z" finished-at="2018-01-11T14:15:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginPageTest()[pri:1, instance:scenarios.AppiumTest@6d00a15d]" name="loginPageTest" duration-ms="5024" started-at="2018-01-11T14:15:38Z" description="Launches the test 1" finished-at="2018-01-11T14:15:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageTest -->
        <test-method status="FAIL" signature="loginPage2Test()[pri:2, instance:scenarios.AppiumTest@6d00a15d]" name="loginPage2Test" duration-ms="5011" started-at="2018-01-11T14:15:43Z" description="Launches the test 2" finished-at="2018-01-11T14:15:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [DEVICE IS READY] but found [DEVICE IS READYs]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [DEVICE IS READY] but found [DEVICE IS READYs]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at pages.LoginPage.loginPage2(LoginPage.java:84)at scenarios.AppiumTest.loginPage2Test(AppiumTest.java:29)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:497)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:497)at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPage2Test -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:scenarios.AppiumTest@6d00a15d]" name="tearDown" is-config="true" duration-ms="1" started-at="2018-01-11T14:15:48Z" finished-at="2018-01-11T14:15:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- scenarios.AppiumTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
